### ISSUE TITLE
How to read "calc" from websocket

### ISSUE THREAD

**Issue by kootenpv** [Crypto-toolbox/btfxwss#101]
```python
import time
from btfxwss import BtfxWss
wss = BtfxWss(key=KEY, secret=SECRET)
wss.start()
time.sleep(2)
wss.authenticate()
wss.calc([{
    "symbol": 'BTCUSD',
    "dir": 1,
    "rate": 800,
    "type": 'EXCHANGE'
}])
```

Afterwards, nothing happens. I believe I have to react to some kind of event from the websocket to get the calc, but I do not know how to find it? The only clue is "calc" but does not appear anywhere else in the code base. What am I missing?

**Comment by nlsdfnbch** [comment]
Hey @kootenpv,
thanks for contributing!

In the current `stable` version on pypi, this isn't correctly implemented - there ought to be a queue for this, which you can `get()` from. In the current `dev` release we've merged all account mesages into a single queue - this includes responses from calls to `calc()`. 

So either wait for the next release, or install the `dev` version via `pip install --pre btfxwss`. Beware though, the interface is not backwards compatible.

**Comment by kootenpv** [comment]
Thanks! So I did, and it still took me some time to figure out, but with the new version I did this:

```python
import time
from btfxwss import BtfxWss
wss = BtfxWss(key=KEY, secret=SECRET)
wss.start()
time.sleep(2)
wss.authenticate()
wss.calc([{
    "symbol": "tXRPBTC",
    "dir": 1,
    "rate": 0.00005146,
    "type": 'EXCHANGE'
}])
wss.account().get()

```
I get as result:

```python
(['n',
  [1513292918661,
   'calc-req',
   None,
   None,
   None,
   None,
   'ERROR',
   {'error': 'format: invalid'}]],
 1513292918.7202454)
```

What is going wrong?

**Comment by nlsdfnbch** [comment]
Have a look at the docs:
https://bitfinex.readme.io/v2/reference#ws-input-calc

**Comment by kootenpv** [comment]
I've also tried:

wss.calc(  [
    ["margin_sym_tBTCUSD"],
    ["position_tBTCUSD"],
    ["wallet_margin_BTC"],
    ["wallet_funding_USD"]
  ])

but that doesn't work. Could you please try it yourself? Let me know if you find some code that works to get any kind of calculation done succesfully (make sure you empty the queue, use your calc, and do a `wss.account().get()`), I believe this is a bug.

**Comment by nlsdfnbch** [comment]
Since the error message is returned by Bitfinex, you should submit a ticket with them.

**Comment by kootenpv** [comment]
Finally I got something that works:

```python
wss.calc(*[
    ["wallet_exchange_NEO"]
  ]) 
```
So to get concrete, I would like to calculate how much I could buy at a certain price in my exchange wallet (https://docs.bitfinex.com/v2/reference#rest-auth-calc-bal-avail). How can I do this :)?

**Comment by kootenpv** [comment]
In the end I would just like to do either a limit or market new order with the maximum possible amount. How could that be done using btfxwss?

**Comment by nlsdfnbch** [comment]
Oh. Well in that case you're using the wrong method!
[`BtfxWss.new_order()`](https://github.com/nlsdfnbch/btfxwss/blob/b4419e326a4d9e82af7f02e39ce1b099153d93bd/btfxwss/client.py#L377) if what you want to use.

**Comment by kootenpv** [comment]
@nlsdfnbch The problem is that for that method I need to calculate an amount (which is based on getting your account balance + the current price + however much bitfinex takes = you need to use "calc available" is what I understand? I don't see how in new_order I can do "buy as much as you can at price X"

**Comment by nlsdfnbch** [comment]
@kootenpv , Sorry, I can't help you with that. However, using the REST API to query the amount available via the method you mentioned and then submitting an order appears to be the way to go.
