### ISSUE TITLE
Can't figure out how to block until subscription is complete

### ISSUE THREAD

**Issue by jrhee17** [Crypto-toolbox/btfxwss#111]
In the example provided, the code waits until subscription is complete by manually waiting 10 seconds

    # Subscribe to some channels
    wss.subscribe_to_ticker('BTCUSD')
    wss.subscribe_to_order_book('BTCUSD')

    # Do something else
    t = time.time()
    while time.time() - t < 10:
        pass

Is there a way I could block until a subscription event is given back? 
For instance, I've been taking advantage of the `Queue` data structure to get data like this:

    ticker_q = wss.tickers('BTCUSD')
    ticker_q.get(block=True)

If not, I would be willing to work on a pull request, let me know what you think!

**Comment by nlsdfnbch** [comment]
@jrhee17,  thanks for bringing this to my attention - specifically the while loop to wait because that is some grade A horseshite code. :'D a simple time.sleep(10) would suffice as well. 

As for the wait on subscription, what's the problem with using the block parameter?

**Comment by jrhee17** [comment]
I believe we are on the same page, I would like to simply call the subscribe method and not handle waiting for subscription to be complete.

i.e) the client code could be changed from 

    wss.subscribe_to_ticker('BTCUSD')
    wss.subscribe_to_order_book('BTCUSD')

    # Do something else
    t = time.time()
    while time.time() - t < 10:
        pass

    # Accessing data stored in BtfxWss:
    ticker_q = wss.tickers('BTCUSD')  # returns a Queue object for the pair.
    while not ticker_q.empty():
        print(ticker_q.get())

to this

    wss.subscribe_to_ticker('BTCUSD')
    ticker_q = wss.tickers('BTCUSD')
    result = ticker_q.get(block=True)

Since we are already using `defaultdict`, I was able to achieve this (at least on my local env) by not throwing a `KeyError` in `client.py:348`

    def tickers(self, pair):
        if key in self.queue_processor.tickers:
            return self.queue_processor.tickers[key]
        else:
            raise KeyError(pair)

to this

    def tickers(self, pair):
        return self.queue_processor.tickers[key]

Since this somewhat changes the code convention drastically, I was wondering if this would cause any issues before going forward.

**Comment by jrhee17** [comment]
Resolved with PR #115
