### ISSUE TITLE
Dealing with time lags

### ISSUE THREAD

**Issue by IlyaSleptsov** [Crypto-toolbox/btfxwss#113]
Hello, @nlsdfnbch.
Thank you very much for this library. I use it to parse data in some intervals. For example, every 20 seconds I do a responce to library to get some tickers info:
```
bitfinex_pairs = ["BTCUSD","LTCUSD","LTCBTC","ETHUSD"]
bitfinex_values = []

wss = BtfxWss()
wss.start()
while not wss.conn.connected.is_set():
    time.sleep(1)

for i in bitfinex_pairs:
    wss.subscribe_to_ticker(i)
time.sleep(10)

While True:
    start = time.time()
    for i in bitfinex_pairs:
            bitfinex_values.append(wss.tickers(i).get()[0][0][6])
    time.sleep(20 - (time.time() - start) )
```
This code pulls new values exactly every 20 seconds taking into account the time for working script. But sometimes I get an error that "time.sleep cannot be negative". It means that this code:
```
    for i in bitfinex_pairs:
            bitfinex_values.append(wss.tickers(i).get()[0][0][6])
```
works more than 20 seconds. That is too much for it, usually it works for 0.1-0.5 a second. Why does this happen? 
Can it be my fault because I parse too many tickers (~12-14)?
Or  such 20-seconds lag is normal?
I record logs but they show that everything is ok.

Thank you!

**Comment by eSanity** [comment]
Changed `time.sleep(20 - (time.time() - start) )` to `time.sleep(max(0, 20 - (time.time() - start)))`
This will at least stop the error from happening.

**Comment by IlyaSleptsov** [comment]
@eSanity Thank you for answer. This solution works but does not provide 20-seconds synchrony. This is very sensitive when working with several exchanges. My question was another: is it really normal that this exchange provides such large gaps like [ 0.1 second - 34 seconds ]. Usually, exchanges give response in [0.1 second - 0.5 second]

**Comment by nlsdfnbch** [comment]
Does this happen frequently, or just on startup? It may be possible that the subscription hasn't been processed yet (leaving you with an empty queue and your `get() ` blocking,  which is what causes the delay) 

In other words, if it's stuck on a get()  call,  that's because no new data has arrived on that queue since the last time you queried it. A solution around this would be to pass ` block=false` and catch the resulting `queue.Empty` exception with a try/except block.

**Comment by IlyaSleptsov** [comment]
@nlsdfnbch Thanks a lot, it works! Problem was in queues, your solution helped me very much.
