### ISSUE TITLE
How to get data from all pairs

### ISSUE THREAD

**Issue by mejmo** [Crypto-toolbox/btfxwss#117]
I would like to catch all pairs (candlers, orderbooks, everything). So what I do is:

        data = json.loads(urllib.request.urlopen("https://api.bitfinex.com/v1/symbols").read())
        pairs = [x.upper() for x in data]

        for pair in pairs:
            self.wss.subscribe_to_trades(pair)
            self.wss.subscribe_to_ticker(pair)
            self.wss.subscribe_to_order_book(pair)
            self.wss.subscribe_to_candles(pair)
            self.wss.subscribe_to_raw_order_book(pair)

Now I'd like to get data. I can go again through all pairs and get data from the queue, but this would be so inefficient. Is there any way to get the data from some general Queue which contains all data from all subscriptions? Thank you.

**Comment by nlsdfnbch** [comment]
Hey @mejmo  ,
For the current release that is indeed the case - there is no single queue to access all data. I'm working on a solution for this on branch using zmq,  but this isn't in a condition to be tested just yet. 
You'll have to fix this locally or wait for the next release.  Sorry!
