### ISSUE TITLE
Unknown Info code 20051!

### ISSUE THREAD

**Issue by dantimofte** [Crypto-toolbox/btfxwss#121]
Problem Description : 
When getting response from api data looks like this : 
data : {'code': 20051, 'msg': 'Stopping. Please try to reconnect'}

When trying to print the error and reconnect it's searching for key as a number : 
![image](https://user-images.githubusercontent.com/4211982/36296428-e9335d84-12f5-11e8-8bf7-3973c53ae61e.png)

while the dictionaries have the key as a string : 
![image](https://user-images.githubusercontent.com/4211982/36296469-0e548278-12f6-11e8-89ee-8f5d3336a8a1.png)

SOLUTION : Either the dictionary keys should be converted to numbers or the response should be converted to string before searching in the dictionary

**Comment by krzysztof-nowak** [comment]
second that :)

**Comment by nlsdfnbch** [comment]
This has been fixed on `dev`! The fix will be merged into `master` and pypi on the next release.

**Comment by dantimofte** [comment]
![image](https://user-images.githubusercontent.com/4211982/36471245-70e4b81e-16f6-11e8-81c6-669e10c627ef.png)
on the dev branch i can see that only the info_message dict has numeric keys. the codes dictionary should also have numeric keys
