### ISSUE TITLE
How can I program a daemon?

### ISSUE THREAD

**Issue by ikarin** [Crypto-toolbox/btfxwss#124]
Hello. I'd like to use this library. 24h I always want to keep getting the price. However, when you look at the sample, the program will end once you get the data. How can I keep acquiring data in an infinite loop?
so is there run_forever function ?

**Comment by nlsdfnbch** [comment]
A daemon is a service that runs in the background - there are many great tutorials and articles on how to achieve this behaviour in python, thus I will not repeat those here.

However, if you'd like to infinitely run the example code replace the `with` block in the example with this:

```python
while True:
    try:
        r = ticker_queue.get()
    except queue.Empty:
        continue
    print(r)
```
