### ISSUE TITLE
Info-message codes type mismatch

### ISSUE THREAD

**Issue by vfvgc** [Crypto-toolbox/btfxwss#133]
# Info messages from server not processed right

### Steps to Reproduce

1. Connect; subscribe to some channels.
2. Keep consuming all events.
3. Wait for an [info message](https://bitfinex.readme.io/v2/docs/ws-general#section-info-messages) such as "20051 : Stop/Restart Websocket Server"

### Actual Results

Exception thrown before getting to call specific info handler such as `self.reconnect`.

```
ERROR:btfxwss.connection:20051
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.5/site-packages/btfxwss/connection.py", line 405, in _info_handler
    self.log.info(info_message[data['code']])
KeyError: 20051
ERROR:btfxwss.connection:Unknown Info code 20051!
```

Looks like the actual received info codes are integers, while the library expects strings (see keys to `info_message` and `codes` in [`WebSocketConnection._info_handler`](https://github.com/Crypto-toolbox/btfxwss/blob/master/btfxwss/connection.py#L403)). By contrast, [error codes](https://github.com/Crypto-toolbox/btfxwss/blob/master/btfxwss/connection.py#L432) are keyed as integers, and seem to be treated right.

### Expected Results

Reconnection/pausing/unpausing gets processed when the corresponding info code is received.

### Reproducibility

Depends on rare-ish server events. Quite sure it would happen every time, though.

### Additional Information:

Using version 1.1.16

**Comment by AdmiralThrawn** [comment]
Been seeing the same occur over the past couple of days:
![image](https://user-images.githubusercontent.com/39618306/41149648-087a32f6-6b04-11e8-8901-aa3b5ec187f7.png)

**Comment by vfvgc** [comment]
I believe master is [fixed](https://github.com/Crypto-toolbox/btfxwss/commit/8d4769b2ba70da1cec716de2177a57c1ae162ed4) already.

**Comment by AdmiralThrawn** [comment]
Agreed. Was seeing the error because the package version obtained via pip does not reflect these changes.
