### ISSUE TITLE
Exchange Market order

### ISSUE THREAD

**Issue by vottghern** [Crypto-toolbox/btfxwss#136]
Hello!

Do you can show me how make a Exchange Market order? And Exchange Limit, please!

Thanks!

**Comment by nlsdfnbch** [comment]
Using btfxwss:
```
b = BtfxWss(**credentials)
# Placing a bid
order_params = { 'cid': 12345, 'type': 'EXCHANGE LIMIT', 'symbol': 'tBTCUSD', 'amount': '0.002', 'price': _rate } bitfinexBot.new_order(**order)
b.new_order(**order_params)
```
If you want to place an `ask` order, prefix the amount with `-` like so:
`'amount':'-0.0002`
