### ISSUE TITLE
Multi thread bug

### ISSUE THREAD

**Issue by numitus** [Crypto-toolbox/btfxwss#139]
https://github.com/Crypto-toolbox/btfxwss/blob/8d4769b2ba70da1cec716de2177a57c1ae162ed4/btfxwss/connection.py#L146-L160

if reconnect and disconnect set at the same time we get infinity loop. it is possible when we disconnect and disconnection raise connection error. disconnect_called=True; reconnect_required=True. and loop never break

**Comment by nlsdfnbch** [comment]
Hey @numitus ,
excellent find! Merging #140 to take care of this. Thanks for the fix!
