### ISSUE TITLE
Timeout settings?

### ISSUE THREAD

**Issue by tr91** [Crypto-toolbox/btfxwss#146]
There was one case where the websocket data stopped coming in for 1 hour. Had to keyboard interrupt it, and start the script from scratch. No error was given at all, just nothing being printed.

Any idea where I should add a (socket) timeout etc?

**Comment by nlsdfnbch** [comment]
Hey @tr91 ,

could you check if the latest dev branch still has this issue ? It may have been taken care of with PR #147.
