### ISSUE TITLE
Websocket configuration is not restored during reconnect

### ISSUE THREAD

**Issue by petr-fedorov** [Crypto-toolbox/btfxwss#148]
As [specified](https://docs.bitfinex.com/v2/docs/ws-general#section-configuration) by Bitfinex API a client may change websocket configuration. This functionality is implemented by [BtfxWss.config()](https://github.com/Crypto-toolbox/btfxwss/blob/42f00f0c78fb9962d47e6d24132a753b1823c54b/btfxwss/client.py#L429) method. Unfortunately the websocket configuration configuration is not saved by this method and as a consequence is not restored during reconnect together with [resubscriptions](https://github.com/Crypto-toolbox/btfxwss/blob/42f00f0c78fb9962d47e6d24132a753b1823c54b/btfxwss/connection.py#L480).

**Comment by nlsdfnbch** [comment]
Thanks, @petr-fedorov !
